//! ppc64 Settings.

use crate::settings::{self, detail, Builder, Value};
use core::fmt;

// Include code generated by `cranelift-codegen/meta/src/gen_settings.rs`.
include!(concat!(env!("OUT_DIR"), "/settings-ppc64.rs"));
